import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="bg-slate-900 text-slate-100 min-h-screen antialiased">
        <header className="border-b border-slate-800 p-4 bg-slate-950/50 backdrop-blur">
          <div className="max-w-7xl mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold tracking-wider text-indigo-400">GLOBAL.SAAS</h1>
            <nav className="space-x-4 text-sm text-slate-400">
              <span className="text-emerald-400">● Server-Rendered Environment</span>
            </nav>
          </div>
        </header>
        <main className="max-w-7xl mx-auto p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
